version: '3'

services:  
   memcached:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - 11111:11211



   sbchainissuer:
      image: endimion13/sbchain:0.0.1
      environment:
         NODE_ENV: "production"
         ENDPOINT: https://dss1.aegean.gr
         HTTPS_COOKIES: "true"
         MEMCACHED_URL: memcached:11211
         BASE_PATH: "sbchain"
      ports:
         - 4040:3000

   



   nginx: 
     image: nginx:latest
     container_name: production_nginx
     volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
     ports:
        - 80:80
        - 443:443
